//text-content

const arr =["Indian law is characterized by its federal structure, with distinct legal systems for the central government, states, and union territories. The judiciary plays a crucial role in interpreting and upholding the law, with the Supreme Court at the apex, followed by High Courts in each state and subordinate courts at various levels. The judiciary also has the power of judicial review, allowing it to strike down laws that violate the constitutional provisions.",
"Indian law is a complex and diverse legal system that has evolved over centuries, drawing from ancient texts, colonial influences, and contemporary developments. The foundation of Indian law can be traced back to ancient texts such as the Manusmriti and Arthashastra, which provided guidelines for social order and governance. Over time, the legal landscape has been shaped by various rulers and empires, including the Mauryas, Guptas, and Mughals, each leaving their imprint on the legal framework.",
"The modern Indian legal system is largely based on the British colonial legacy, with the introduction of the Indian Penal Code, the Code of Criminal Procedure, and the Indian Evidence Act during the colonial period. Post-independence, the Constitution of India, adopted in 1950, became the supreme law of the land, laying down the fundamental rights and duties of citizens and establishing the framework for the government.",
"The legal system in India covers a wide range of areas, including criminal law, civil law, family law, property law, and constitutional law. It is a blend of codified and uncodified laws, with statutes, precedents, and customs all contributing to the legal landscape. The Indian legal profession is well-established, with the Bar Council of India regulating the practice of law and setting ethical standards for lawyers.",
"The legal framework in India also addresses issues related to social justice, with affirmative action measures to uplift marginalized communities. The Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act and other protective legislations aim to safeguard the rights of historically disadvantaged groups.",
"Intellectual property laws in India have evolved to align with international standards, providing protection for patents, trademarks, copyrights, and trade secrets. Additionally, environmental laws have gained significance, reflecting the growing concern for sustainable development and ecological balance.",
"While Indian law has made significant strides in addressing various aspects of society, challenges persist. Issues such as corruption, backlog of cases, and the need for legal literacy remain areas that require continuous attention and reform. The dynamic nature of Indian law reflects the nation's commitment to adapting its legal system to meet the evolving needs of its diverse population."]

const random1 = arr[(Math.floor(Math.random()*(arr.length)))];
var text = random1
document.getElementById("text-content").innerHTML= text;